### ISSUE TITLE
Github Release 1.0.5 is missing

### ISSUE THREAD

**Issue by bmarwell** [yupiik/yupiik-logging#1]
Hey,

I see a tag 1.0.5 on GitHub and dependabot and renovate PRs. But no release on GitHub, so no changelog unless you compare tags :)

**Comment by rmannibucau** [comment]
Fixed manually.

For the story, it is synch-ed once a week thanks https://github.com/yupiik/yupiik.github.io/actions so was "normal" ;).

**Comment by bmarwell** [comment]
Great! I was just wondering about dependabot and renovate not giving me a changelog 😉
